In [24]:
from sklearn.svm import SVR
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.metrics import r2_score
from sklearn import datasets

In [25]:
df = datasets.load_diabetes(as_frame=True).frame

In [26]:
df.head()

,age,sex,bmi,bp,s1,s2,s3,s4,s5,s6,target
0,0.038076,0.050680,0.061696,0.021872,-0.044223,-0.034821,-0.043401,-0.002592,0.019907,-0.017646,151.0
1,-0.001882,-0.044642,-0.051474,-0.026328,-0.008449,-0.019163,0.074412,-0.039493,-0.068332,-0.092204,75.0
2,0.085299,0.050680,0.044451,-0.005670,-0.045599,-0.034194,-0.032356,-0.002592,0.002861,-0.025930,141.0
3,-0.089063,-0.044642,-0.011595,-0.036656,0.012191,0.024991,-0.036038,0.034309,0.022688,-0.009362,206.0
4,0.005383,-0.044642,-0.036385,0.021872,0.003935,0.015596,0.008142,-0.002592,-0.031988,-0.046641,135.0


In [27]:
df.shape

(442, 11)

In [28]:
X = df.drop("target", axis=1)
y = df["target"]

In [29]:
X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.3, random_state=42
)

In [30]:
y_scaler = StandardScaler()

y_train_scaled = y_scaler.fit_transform(y_train.values.reshape(-1, 1)).ravel()
y_test_scaled = y_scaler.transform(y_test.values.reshape(-1, 1)).ravel()

In [31]:
y_train_scaled

array([ 6.89917243e-01,  1.36584298e+00,  3.20071083e-01,  1.32758304e+00,
        1.37859630e+00, -1.31235335e+00,  1.05976340e+00, -1.05728703e+00,
       -1.90061552e-01,  1.45511620e+00, -1.08279366e+00,  2.08002867e+00,
        1.21280319e+00,  1.23818601e-03,  4.85864189e-01, -4.83387817e-01,
       -9.29753873e-01, -4.06867922e-01,  1.34033635e+00,  4.73110873e-01,
        1.76119578e+00, -1.26134009e+00, -5.98167660e-01,  7.15423875e-01,
       -8.02220714e-01,  1.26381646e+00, -8.78740609e-01,  1.25106314e+00,
       -1.21032682e+00, -9.68013820e-01,  5.87890716e-01, -9.68013820e-01,
        1.16178993e+00,  2.69057819e-01, -1.42713319e+00, -3.43101343e-01,
       -1.28684672e+00, -7.63960766e-01, -6.36427608e-01,  5.75137400e-01,
        1.41685625e+00,  1.62090930e+00,  1.20004988e+00,  1.31482972e+00,
        7.79190454e-01,  1.90148225e+00,  2.05291240e-01, -1.21032682e+00,
        1.56989604e+00,  7.02670559e-01, -2.02814868e-01,  5.62384084e-01,
       -3.81361290e-01, -

In [32]:
y_test_scaled

array([ 0.83020372, -1.07004035,  0.61339735,  0.97049019, -0.5471544 ,
       -0.89149393,  1.12352998,  1.50612946, -0.76396077, -0.73845413,
       -0.76396077,  1.25106314, -0.70019419,  1.82496236, -0.24107482,
       -1.10830029,  1.79945572,  1.40410293,  0.20529124,  1.54438941,
        1.99075546, -1.14656024, -0.33034803,  0.99599682, -0.31759471,
       -0.45788119,  1.39134962, -0.98076714, -1.3506133 , -0.59816766,
       -0.17730824, -0.52164776, -0.81497403,  0.12877134,  0.3328244 ,
        1.00875014, -1.42713319, -0.89149393,  0.23079787, -1.15931356,
       -1.3506133 , -0.58541434,  0.02674482,  0.17978461, -0.81497403,
       -1.29960003,  0.58789072, -0.85323398, -0.81497403,  1.32758304,
       -0.2283215 ,  0.05225145, -1.08279366, -1.04453372,  0.21804456,
       -0.75120745, -1.04453372, -0.03702176,  0.17978461, -1.19757351,
       -0.40686792, -1.29960003,  0.42209761, -0.66193424,  0.76643714,
        1.20004988,  0.34557771, -0.55990771, -0.17730824,  0.61

In [33]:
model = SVR()

model.fit(X_train, y_train_scaled)

SVR()

In [34]:
y_test_pred_scaled = model.predict(X_test)
y_train_pred_scaled = model.predict(X_train)

In [35]:
y_test_pred_scaled

array([-0.2885577 ,  0.39931628,  0.07692266,  0.995732  , -0.59136691,
       -0.43552618,  1.50419599,  0.57125595, -0.68236562, -0.6443524 ,
       -0.59030709,  0.4288888 , -0.65363754,  0.78858785, -1.23085396,
       -0.87137134,  1.27758172,  1.60161223,  0.33411691,  1.28963082,
        0.59868459, -0.89042023, -1.16315936,  0.75689988, -0.13872588,
       -0.18259671,  0.79073542, -0.24331395, -1.11276337, -0.79045401,
        0.12653539,  0.13014631, -0.76942897, -0.04528934, -0.10509827,
        0.50858033, -0.95700587, -0.64870942, -0.00428037, -1.20353503,
       -0.95940501, -0.61444661,  0.07019339, -0.03408375,  0.26930624,
       -0.84518006, -0.67681023, -0.54078067, -1.12064401,  0.11940571,
       -0.32618471, -0.37923049, -0.1902295 , -0.83409117,  0.46443229,
       -0.14819543, -0.5717283 ,  1.04295498, -0.65328786, -1.00909137,
        0.28278263,  0.79155218, -0.73876009, -0.98934941, -0.08623679,
        0.48789642,  0.39851386,  0.11430449,  0.23610019, -0.54

In [36]:
print("train r2: ", r2_score(y_train_scaled, y_train_pred_scaled))
print("test r2: ", r2_score(y_test_scaled, y_test_pred_scaled))

train r2:  0.6596361676267712
test r2:  0.48844443151651884


In [37]:
# Linear
model = SVR(kernel="linear")

model.fit(X_train, y_train_scaled)

y_test_pred_scaled = model.predict(X_test)
y_train_pred_scaled = model.predict(X_train)

print("train r2: ", r2_score(y_train_scaled, y_train_pred_scaled))
print("test r2: ", r2_score(y_test_scaled, y_test_pred_scaled))

train r2:  0.45191229982475245
test r2:  0.4433761323833776


In [38]:
# Linear
model = SVR(kernel="poly")

model.fit(X_train, y_train_scaled)

y_test_pred_scaled = model.predict(X_test)
y_train_pred_scaled = model.predict(X_train)

print("train r2: ", r2_score(y_train_scaled, y_train_pred_scaled))
print("test r2: ", r2_score(y_test_scaled, y_test_pred_scaled))

train r2:  0.5790920834310542
test r2:  0.24203771038107758


# Hyperparameter tuning usign GridSearchCV

In [39]:
from sklearn.model_selection import GridSearchCV

In [40]:
param_grid = {
    "C": [1, 2, 5, 10, 50, 100],
    "kernel": ["rbf", "linear"],
    "epsilon": [0.01, 0.1, 0.2, 0.3, 0.5]
}

In [41]:
svr = SVR()

grid_search = GridSearchCV(svr, param_grid, scoring="r2", cv=5)

grid_search.fit(X_train, y_train_scaled)

GridSearchCV(cv=5, estimator=SVR(),
             param_grid={'C': [1, 2, 5, 10, 50, 100],
                         'epsilon': [0.01, 0.1, 0.2, 0.3, 0.5],
                         'kernel': ['rbf', 'linear']},
             scoring='r2')

In [42]:
print("best params - ", grid_search.best_params_)

best params -  {'C': 10, 'epsilon': 0.1, 'kernel': 'linear'}


In [43]:
best_model = SVR(kernel="linear", C=10, epsilon=0.1)

best_model.fit(X_train, y_train_scaled)

y_test_pred_scaled = best_model.predict(X_test)
y_train_pred_scaled = best_model.predict(X_train)

print("train r2: ", r2_score(y_train_scaled, y_train_pred_scaled))
print("test r2: ", r2_score(y_test_scaled, y_test_pred_scaled))

train r2:  0.5151066486918876
test r2:  0.47444183250401095


In [23]:
from sklearn.svm import LinearSVR

model = LinearSVR(C=10, epsilon=0.1, max_iter=5000)

model.fit(X_train, y_train_scaled)

y_test_pred_scaled = model.predict(X_test)
y_train_pred_scaled = model.predict(X_train)

print("train r2: ", r2_score(y_train_scaled, y_train_pred_scaled))
print("test r2: ", r2_score(y_test_scaled, y_test_pred_scaled))

train r2:  0.5153286104313408
test r2:  0.47494982848066114
